/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import java.awt.Dimension;

/**
 *
 * @author raulv
 */
public class PhotofilterRGB extends javax.swing.JFrame {

    private static boolean redFilter;
    private static boolean blueFilter;
    private static boolean greenFilter;
    /**
     * Creates new form PhotofilterRGB
     */
    public PhotofilterRGB() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        groupLocationButton = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        TodosButton = new javax.swing.JCheckBox();
        RedButton = new javax.swing.JCheckBox();
        GreenButton = new javax.swing.JCheckBox();
        BlueButton = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        SupIzqButton = new javax.swing.JRadioButton();
        InfIzqButton = new javax.swing.JRadioButton();
        SupDerButton = new javax.swing.JRadioButton();
        InfDerButton = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lienzo1 = new UI.Lienzo();

        jLabel3.setText("Elija el filtro a aplicar en imagen:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Photofilter RGB");

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        TodosButton.setSelected(true);
        TodosButton.setText("Todos");
        TodosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TodosButtonActionPerformed(evt);
            }
        });

        RedButton.setSelected(true);
        RedButton.setText("Rojo");
        RedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RedButtonActionPerformed(evt);
            }
        });

        GreenButton.setSelected(true);
        GreenButton.setText("Verde");
        GreenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GreenButtonActionPerformed(evt);
            }
        });

        BlueButton.setSelected(true);
        BlueButton.setText("Azul");
        BlueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BlueButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(GreenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BlueButton)
                    .addComponent(TodosButton)
                    .addComponent(RedButton))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TodosButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RedButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GreenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BlueButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        groupLocationButton.add(SupIzqButton);
        SupIzqButton.setSelected(true);
        SupIzqButton.setText("Superior izquierda");
        SupIzqButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupIzqButtonActionPerformed(evt);
            }
        });

        groupLocationButton.add(InfIzqButton);
        InfIzqButton.setText("Inferior izquierda");
        InfIzqButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InfIzqButtonActionPerformed(evt);
            }
        });

        groupLocationButton.add(SupDerButton);
        SupDerButton.setText("Superior derecha");
        SupDerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupDerButtonActionPerformed(evt);
            }
        });

        groupLocationButton.add(InfDerButton);
        InfDerButton.setText("Inferior derecha");
        InfDerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InfDerButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(SupIzqButton)
                    .addComponent(InfIzqButton, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SupDerButton, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(InfDerButton, javax.swing.GroupLayout.Alignment.LEADING)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SupIzqButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InfIzqButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SupDerButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(InfDerButton)
                .addContainerGap())
        );

        jLabel2.setText("Elija el filtro a aplicar en imagen:");

        jLabel4.setText("Elija la localización del logo:");

        lienzo1.setPreferredSize(new java.awt.Dimension(1024, 768));

        javax.swing.GroupLayout lienzo1Layout = new javax.swing.GroupLayout(lienzo1);
        lienzo1.setLayout(lienzo1Layout);
        lienzo1Layout.setHorizontalGroup(
            lienzo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 982, Short.MAX_VALUE)
        );
        lienzo1Layout.setVerticalGroup(
            lienzo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 671, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(498, 498, 498)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lienzo1, javax.swing.GroupLayout.PREFERRED_SIZE, 982, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)))
                .addGap(154, 154, 154))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(221, 221, 221)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 329, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lienzo1, javax.swing.GroupLayout.PREFERRED_SIZE, 671, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RedButtonActionPerformed
        redFilter = RedButton.isSelected();
        blueFilter = BlueButton.isSelected();
        greenFilter = GreenButton.isSelected();
        
        if(greenFilter || blueFilter){
            TodosButton.setSelected(false);
            this.lienzo1.setFilters(RedButton.isSelected(),GreenButton.isSelected(),BlueButton.isSelected());
        }else{
            RedButton.setSelected(true);
        }
        
        if(redFilter && blueFilter && greenFilter){
            TodosButton.setSelected(true);
        }
    }//GEN-LAST:event_RedButtonActionPerformed

    private void SupIzqButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupIzqButtonActionPerformed
        this.lienzo1.moveLogo(0,0);
    }//GEN-LAST:event_SupIzqButtonActionPerformed

    private void TodosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TodosButtonActionPerformed
            TodosButton.setSelected(true);
            RedButton.setSelected(true);
            BlueButton.setSelected(true);
            GreenButton.setSelected(true);
            this.lienzo1.setFilters(RedButton.isSelected(),GreenButton.isSelected(),BlueButton.isSelected());
    }//GEN-LAST:event_TodosButtonActionPerformed

    private void GreenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GreenButtonActionPerformed
        redFilter = RedButton.isSelected();
        blueFilter = BlueButton.isSelected();
        greenFilter = GreenButton.isSelected();
        
        if(redFilter || blueFilter){
            TodosButton.setSelected(false);
            this.lienzo1.setFilters(RedButton.isSelected(),GreenButton.isSelected(),BlueButton.isSelected());
        }else{
            GreenButton.setSelected(true);
        }
        
        if(redFilter && blueFilter && greenFilter){
            TodosButton.setSelected(true);
        }
    }//GEN-LAST:event_GreenButtonActionPerformed

    private void BlueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BlueButtonActionPerformed
        redFilter = RedButton.isSelected();
        blueFilter = BlueButton.isSelected();
        greenFilter = GreenButton.isSelected();
        
        if(redFilter || greenFilter){
            TodosButton.setSelected(false);
            this.lienzo1.setFilters(RedButton.isSelected(),GreenButton.isSelected(),BlueButton.isSelected());
        }else{
            BlueButton.setSelected(true);
        }   
        
        if(redFilter && blueFilter && greenFilter){
            TodosButton.setSelected(true);
        }
    }//GEN-LAST:event_BlueButtonActionPerformed

    private void InfIzqButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InfIzqButtonActionPerformed
        Dimension dimensionesImagen = this.lienzo1.getImageDimensions();
        Dimension dimensionesLogo = this.lienzo1.getLogoDimensions();
        this.lienzo1.moveLogo(0, (int) (dimensionesImagen.getHeight() - dimensionesLogo.height));
    }//GEN-LAST:event_InfIzqButtonActionPerformed

    private void SupDerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupDerButtonActionPerformed
        Dimension dimensionesImagen = this.lienzo1.getImageDimensions();
        Dimension dimensionesLogo = this.lienzo1.getLogoDimensions();
        this.lienzo1.moveLogo((int) (dimensionesImagen.getWidth() - dimensionesLogo.width), 0);
    }//GEN-LAST:event_SupDerButtonActionPerformed

    private void InfDerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InfDerButtonActionPerformed
        Dimension dimensionesImagen = this.lienzo1.getImageDimensions();
        Dimension dimensionesLogo = this.lienzo1.getLogoDimensions();
        this.lienzo1.moveLogo((int) (dimensionesImagen.getWidth() - dimensionesLogo.width), (int) (dimensionesImagen.getHeight() - dimensionesLogo.height));
    }//GEN-LAST:event_InfDerButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PhotofilterRGB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PhotofilterRGB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PhotofilterRGB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PhotofilterRGB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PhotofilterRGB().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox BlueButton;
    private javax.swing.JCheckBox GreenButton;
    private javax.swing.JRadioButton InfDerButton;
    private javax.swing.JRadioButton InfIzqButton;
    private javax.swing.JCheckBox RedButton;
    private javax.swing.JRadioButton SupDerButton;
    private javax.swing.JRadioButton SupIzqButton;
    private javax.swing.JCheckBox TodosButton;
    private javax.swing.ButtonGroup groupLocationButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private UI.Lienzo lienzo1;
    // End of variables declaration//GEN-END:variables
}
